### ISSUE TITLE
(1) [Dunning] Patch to create boilerplate texts

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#47] opened 2020-06-02 09:11 UTC
Patch to create boilerplate texts for existing instances and new setups

**Comment by jeremythegreat01** [comment] 2021-06-22 07:45
Un-assigning from Kanchan because she is offboarding.

Adding this to the backlog project.

**Comment by jeremythegreat01** [comment] 2022-01-26 07:28
Closing this to clean up the queue and because the issue is from 2020.

If users still need the feature, a new issue should be created with better information.

**Closed as completed by jeremythegreat01** 2022-01-26 07:28 UTC
Labels: enhancement
