### ISSUE TITLE
(1) [Dunning] Patch for migrating data

### ISSUE THREAD

**Issue by dottenbr** [newmatik/dunning#46] opened 2020-06-02 09:11 UTC
Patch for migrating data for users who have app installed

**Comment by jeremythegreat01** [comment] 2021-06-22 07:44
Un-assigning from Kanchan because she is offboarding.

Adding this to the backlog project.

**Comment by jeremythegreat01** [comment] 2022-01-26 07:27
Closing this to clean up the queue and because the issue is from 2020.

If users still need the feature, a new issue should be created with better information.

**Closed as completed by jeremythegreat01** 2022-01-26 07:27 UTC
